#!/bin/sh
rm -rf Payload
rm -rf new.ipa 
rm -rf temp.plist
security cms -D -i embedded.mobileprovision >>temp.plist
unzip rd.ipa 
targetApp=rdMyApp.app
TARGET_APP_PATH=Payload/$targetApp
TARGET_APP_FRAMEWORKS_PATH="$TARGET_APP_PATH/Frameworks"
rm -rf Payload/$targetApp/_CodeSignature/

rm -rf Payload/$targetApp/Frameworks/XCTest.framework//_CodeSignature/
codesign -f -s "iPhone Distribution: Techno Construction LLC" Payload/$targetApp/Frameworks/XCTest.framework/
codesign -f -s "iPhone Distribution: Techno Construction LLC" --entitlements entitlements.plist Payload/$targetApp

zip -q -r new.ipa Payload
